services:
  - type: web
    name: liberate-khorasan-frontend
    runtime: node
    plan: free
    buildCommand: cd frontend && rm -rf .next && npm install && npm run build
    startCommand: cd frontend && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  - type: web
    name: liberate-khorasan-backend
    runtime: node
    plan: free
    buildCommand: cd backend/LIBERATEKHURASAN && npm install && npm run build
    startCommand: cd backend/LIBERATEKHURASAN && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
